services:
  cf-dns-updater:
    container_name: cf-dns-updater
    image: python:3.9-slim
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "pip install --no-cache-dir -r requirements.txt && python app.py"
    environment:
      - CONFIG_FILE=config.json
    restart: always
