services:
  cf-dns-updater:
    container_name: cf-dns-updater
    build: .
    image: cf-dns-updater:latest
    volumes:
      - .:/app
    environment:
      - CONFIG_FILE=config.json
    restart: always
